thfmsemi/Controllers/LoginFirstPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using thfmsemi.Models;
namespace thfmsemi.Controllers
{
    public class LoginFirstPageController : Controller
    {
        // GET: LoginFirstPage
        public ActionResult Index()
        {
            using (Entities db = new Entities())
            {
                return View(db.Logins.ToList());
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login user)
        {
            using (Entities db = new Entities())
            {
                var usr = db.Logins.Where(u => u.l_Email == user.l_Email && u.Password == user.Password).FirstOrDefault();
                if (usr != null)
                {
                    Session["UserID"] = usr.Login_Id.ToString();
                    Session["FirstName"] = usr.l_Firstname.ToString();
                    Session["LastName"] = usr.l_Lastname.ToString();
                    Session["Email"] = usr.l_Email.ToString();
                    return RedirectToAction("Create", "Registers");
                }
                else
                {
                    ModelState.AddModelError("", "อีเมล์ หรือ รหัสผ่าน ผิดพลาด.");
                }
            }
            return View();
        }
    }
}

thfmsemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - THFM Seminar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<meta name="description" content="The description of my page" />*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The 2nd Thailand Healthcare Facility Management Excellence Seminar", "Login", "LoginFirstPage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>สวัสดีค่ะ คุณ @Session["FirstName"].ToString() @Session["LastName"].ToString()</li>
                    </ul>
                </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RFS Co.,Ltd.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>