thfmsemi/Models/Login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thfmsemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.Registers = new HashSet<Register>();
            this.Bills = new HashSet<Bill>();
        }
    
        public int Login_Id { get; set; }
        [Required(ErrorMessage = "Firstname is required.")]
        public string l_Firstname { get; set; }
        [Required(ErrorMessage = "Lastname is required.")]
        public string l_Lastname { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
    ErrorMessage = "Please enter a valid e-mail adress")]
        public string l_Email { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage = "Please confirm your password.")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}

thfmsemi/Controllers/LoginFirstPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using thfmsemi.Models;
namespace thfmsemi.Controllers
{
    public class LoginFirstPageController : Controller
    {
        // GET: LoginFirstPage
        public ActionResult Index()
        {
            using (Entities db = new Entities())
            {
                return View(db.Logins.ToList());
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Login user)
        {
            using (Entities db = new Entities())
            {
                var usr = db.Logins.Where(u => u.l_Email == user.l_Email && u.Password == user.Password).FirstOrDefault();
                if (usr != null)
                {
                    Session["UserID"] = usr.Login_Id.ToString();
                    Session["FirstName"] = usr.l_Firstname.ToString();
                    Session["LastName"] = usr.l_Lastname.ToString();
                    Session["Email"] = usr.l_Email.ToString();
                    return RedirectToAction("Create", "Registers");
                }
                else
                {
                    ModelState.AddModelError("", "อีเมล์ หรือ รหัสผ่าน ผิดพลาด.");
                }
            }
            return View();
        }
    }
}

thfmsemi/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thfmsemi.Models;

namespace thfmsemi.Controllers
{
    public class LoginsController : Controller
    {
        private Entities db = new Entities();

        // GET: Logins
        public ActionResult Index()
        {
            return View(db.Logins.ToList());
        }

        // GET: Logins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // GET: Logins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Logins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Login_Id,l_Firstname,l_Lastname,l_Email,Password,ConfirmPassword")] Login login)
        {
            var mail = db.Logins.Where(u => u.l_Email == login.l_Email).FirstOrDefault();
            if (mail == null)
            {
                if (ModelState.IsValid)
                {
                    db.Logins.Add(login);
                    db.SaveChanges();
                    Session["Email"] = login.l_Email.ToString();
                    Session["UserID"] = login.Login_Id.ToString();
                    Session["FirstName"] = login.l_Firstname.ToString();
                    Session["LastName"] = login.l_Lastname.ToString();
                    //var Reg = new RegistersController();
                    //Reg._UserId = Session["UserID"].ToString();
                    return RedirectToAction("Create", "Registers");
                }
            }
            else
            {
                ModelState.AddModelError("", "ไม่สามารถใช้อีเมล์นี้ได้ มีอีเมล์นี้อยู่ในระบบแล้ว");
            }
            return View(login);
        }

        // GET: Logins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Login_Id,l_Firstname,l_Lastname,l_Email,Password,ConfirmPassword")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Login login = db.Logins.Find(id);
            db.Logins.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

thfmsemi/Views/LoginFirstPage/Login.cshtml
@model thfmsemi.Models.Login

@{
    ViewBag.Title = "Login";
}

<h2>ยินดีต้อนรับสู่ระบบลงทะเบียนผู้เข้าร่วมสัมมนา</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>The 2<sup>nd</sup> Thailand Healthcare Facility Management Excellence Seminar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.l_Email, "อีเมล์", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.l_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.l_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, "รหัสผ่าน", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="เข้าสู่ระบบ" class="btn btn-success" onclick="DisableButton(this);" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    @Html.ActionLink("สมัครสมาชิก", "Create", "Logins") ||
    @Html.ActionLink("ลืมรหัสผ่าน", "Form", "Email")
</div>
<div>
    <p style="text-align: left;"><img src="~/img/Sponser.png" width="70%" height="70%" /></p>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
   function DisableButton(b)
   {
      b.disabled = true
      b.value = 'เข้าสู่ระบบ...';
      b.form.submit();
   }
</script>