thfmsemi/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thfmsemi.Models;

namespace thfmsemi.Controllers
{
    public class BillsController : Controller
    {
        private Entities db = new Entities();

        // GET: Bills
        public ActionResult Index()
        {
            var bills = db.Bills.Include(b => b.BillType).Include(b => b.CompanyType).Include(b => b.Login).Include(b => b.Rate1).Include(b => b.Register);
            return View(bills.ToList());
        }

        // GET: Bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            if (Session["UserID"] != null)
            {
                ViewBag.BillType_Id = new SelectList(db.BillTypes, "BillType_Id", "BillType_Name");
                ViewBag.CompanyType_Id = new SelectList(db.CompanyTypes, "CompanyType_Id", "CompanyType_Name");
                ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname");
                ViewBag.Rate = new SelectList(db.Rates, "Rate1", "Rate1");
                ViewBag.Register_Id = new SelectList(db.Registers, "Register_Id", "Titlename");
                return View();
            }
            else
            {
                return RedirectToAction("Login", "LoginFirstPage");
            }
        }

        // POST: Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Bill_Id,CompanyType_Id,CompanyName,Contact_Firstname,Contact_Lastname,Tel,Fax,Tex,Rate,Price,Address_1,Township_1,Amphoe_1,Province_1,ZipCode_1,AddressSend,TownshipSend,AmphoeSend,ProvinceSend,ZipCodeSend,BillType_Id,Register_Id,Login_Id,chk")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                //(ราคา * จำนวนคน) - ((ราคา * จำนวนคน) / 1.07) * อัตราภาษี)
                double _Rate = Convert.ToDouble(bill.Rate.ToString());
                var SumMoney = (3000 * 1) - ((((3000 * 1) / 1.07) * _Rate) / 100);
                string sql = @"UPDATE Bills SET 
                                                CompanyType_Id = {0},
                                                CompanyName = {1},
                                                Contact_Firstname = {2},
                                                Contact_Lastname = {3},
                                                Tel = {4},
                                                Fax = {5},
                                                Tex = {6},
                                                Rate = {7},
                                                Price = {8},
                                                Address_1 = {9},
                                                Township_1 = {10},
                                                Amphoe_1 = {11},
                                                Province_1 = {12},
                                                ZipCode_1 = {13},
                                                AddressSend = {14},
                                                TownshipSend = {15},
                                                AmphoeSend = {16},
                                                ProvinceSend = {17},
                                                ZipCodeSend = {18},
                                                BillType_Id = {19},
                                                chk = 1
                             WHERE Login_Id ={20} AND chk = 0";
                List<Object> sqlParamsList = new List<object>();
                sqlParamsList.Add(bill.CompanyType_Id);//0
                sqlParamsList.Add(bill.CompanyName);//1
                sqlParamsList.Add(bill.Contact_Firstname);//2
                sqlParamsList.Add(bill.Contact_Lastname);//3
                sqlParamsList.Add(bill.Tel);//4
                sqlParamsList.Add(bill.Fax);//5
                sqlParamsList.Add(bill.Tex);//6
                sqlParamsList.Add(bill.Rate);//7 
                sqlParamsList.Add(SumMoney);//8
                sqlParamsList.Add(bill.Address_1);//9
                sqlParamsList.Add(bill.Township_1);//10
                sqlParamsList.Add(bill.Amphoe_1);//11
                sqlParamsList.Add(bill.Province_1);//12
                sqlParamsList.Add(bill.ZipCode_1);//13
                sqlParamsList.Add(bill.AddressSend);//14
                sqlParamsList.Add(bill.TownshipSend);//15
                sqlParamsList.Add(bill.AmphoeSend);//16
                sqlParamsList.Add(bill.ProvinceSend);//17
                sqlParamsList.Add(bill.ZipCodeSend);//18
                sqlParamsList.Add(bill.BillType_Id);//19
                sqlParamsList.Add(Convert.ToInt32(Session["UserID"]));//20
                db.Database.ExecuteSqlCommand(sql, sqlParamsList.ToArray());
                //db.Bills.Add(bill);
                //db.SaveChanges();
                int a = Convert.ToInt32(Session["UserID"]);
                //var ds = (from c in db.Registers
                //         where c.Login_Id == a && c.StatusPay_Id == 1
                //         select c).FirstOrDefault();
                //if(ds != null)
                //{
                //    ds.StatusPay_Id = 2;

                //}
                //db.SaveChanges();
                string sql2 = @"UPDATE Register SET StatusPay_Id = 2 WHERE Login_Id ={0} AND StatusPay_Id = 1";
                List<Object> sqlParamsList2 = new List<object>();
                sqlParamsList2.Add(a);//0
                db.Database.ExecuteSqlCommand(sql2, sqlParamsList2.ToArray());
                return RedirectToAction("Index", "Reports");
            }

            ViewBag.BillType_Id = new SelectList(db.BillTypes, "BillType_Id", "BillType_Name", bill.BillType_Id);
            ViewBag.CompanyType_Id = new SelectList(db.CompanyTypes, "CompanyType_Id", "CompanyType_Name", bill.CompanyType_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", bill.Login_Id);
            ViewBag.Rate = new SelectList(db.Rates, "Rate1", "Rate1", bill.Rate);
            ViewBag.Register_Id = new SelectList(db.Registers, "Register_Id", "Titlename", bill.Register_Id);
            return View(bill);
        }

        // GET: Bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillType_Id = new SelectList(db.BillTypes, "BillType_Id", "BillType_Name", bill.BillType_Id);
            ViewBag.CompanyType_Id = new SelectList(db.CompanyTypes, "CompanyType_Id", "CompanyType_Name", bill.CompanyType_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", bill.Login_Id);
            ViewBag.Rate = new SelectList(db.Rates, "Rate1", "Rate1", bill.Rate);
            ViewBag.Register_Id = new SelectList(db.Registers, "Register_Id", "Titlename", bill.Register_Id);
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Bill_Id,CompanyType_Id,CompanyName,Contact_Firstname,Contact_Lastname,Tel,Fax,Tex,Rate,Price,Address_1,Township_1,Amphoe_1,Province_1,ZipCode_1,AddressSend,TownshipSend,AmphoeSend,ProvinceSend,ZipCodeSend,BillType_Id,Register_Id,Login_Id")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillType_Id = new SelectList(db.BillTypes, "BillType_Id", "BillType_Name", bill.BillType_Id);
            ViewBag.CompanyType_Id = new SelectList(db.CompanyTypes, "CompanyType_Id", "CompanyType_Name", bill.CompanyType_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", bill.Login_Id);
            ViewBag.Rate = new SelectList(db.Rates, "Rate1", "Rate1", bill.Rate);
            ViewBag.Register_Id = new SelectList(db.Registers, "Register_Id", "Titlename", bill.Register_Id);
            return View(bill);
        }

        // GET: Bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = db.Bills.Find(id);
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)

thfmsemi/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thfmsemi.Models;

namespace thfmsemi.Controllers
{
    public class RegistersController : Controller
    {
        private Entities db = new Entities();

        // GET: Registers
        public ActionResult Index()
        {
            var registers = db.Registers.Include(r => r.ClassroomDay1).Include(r => r.ClassroomDay2).Include(r => r.Login).Include(r => r.StatusPay);
            return View(registers.ToList());
        }

        // GET: Registers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // GET: Registers/Create
        public ActionResult Create()
        {
            if (Session["UserID"] != null)
            {
                int a = Convert.ToInt32(Session["UserID"]);
                var Name = db.Registers.Where(s => s.Login_Id == a).ToList();
                if (Name != null)
                {
                    ViewBag.Name = Name;
                    ViewBag.ClassroomDay1_Id = new SelectList(db.ClassroomDay1, "ClassroomDay1_Id", "ClassroomDay1_Name");
                    ViewBag.ClassroomDay2_Id = new SelectList(db.ClassroomDay2, "ClassroomDay2_Id", "ClassroomDay2_Name");
                    ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname");
                    ViewBag.StatusPay_Id = new SelectList(db.StatusPays, "StatusPay_Id", "StatusPay_Name");
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login", "LoginFirstPage");
            }
        }

        // POST: Registers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Register_Id,Titlename,Firstname,Lastname,Position,Email,Tel,ClassroomDay1_Id,ClassroomDay2_Id,StatusPay_Id,DateRegister,DateChk,Login_Id")] Register register)
        {
            if (ModelState.IsValid)
            {
                db.Registers.Add(register);
                register.Login_Id = Convert.ToInt32(Session["UserID"]);
                register.StatusPay_Id = 1;
                db.SaveChanges();
                //Add Bill
                db.Bills.Add(new Bill()
                {
                    Login_Id = Convert.ToInt32(Session["UserID"]),
                    Register_Id = register.Register_Id,
                    Rate = 0,
                    Price = "3000",
                    chk = 0
                });
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.ClassroomDay1_Id = new SelectList(db.ClassroomDay1, "ClassroomDay1_Id", "ClassroomDay1_Name", register.ClassroomDay1_Id);
            ViewBag.ClassroomDay2_Id = new SelectList(db.ClassroomDay2, "ClassroomDay2_Id", "ClassroomDay2_Name", register.ClassroomDay2_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", register.Login_Id);
            ViewBag.StatusPay_Id = new SelectList(db.StatusPays, "StatusPay_Id", "StatusPay_Name", register.StatusPay_Id);
            return View(register);
        }

        // GET: Registers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassroomDay1_Id = new SelectList(db.ClassroomDay1, "ClassroomDay1_Id", "ClassroomDay1_Name", register.ClassroomDay1_Id);
            ViewBag.ClassroomDay2_Id = new SelectList(db.ClassroomDay2, "ClassroomDay2_Id", "ClassroomDay2_Name", register.ClassroomDay2_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", register.Login_Id);
            ViewBag.StatusPay_Id = new SelectList(db.StatusPays, "StatusPay_Id", "StatusPay_Name", register.StatusPay_Id);
            return View(register);
        }

        // POST: Registers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Register_Id,Titlename,Firstname,Lastname,Position,Email,Tel,ClassroomDay1_Id,ClassroomDay2_Id,StatusPay_Id,DateRegister,DateChk,Login_Id")] Register register)
        {
            if (ModelState.IsValid)
            {
                db.Entry(register).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClassroomDay1_Id = new SelectList(db.ClassroomDay1, "ClassroomDay1_Id", "ClassroomDay1_Name", register.ClassroomDay1_Id);
            ViewBag.ClassroomDay2_Id = new SelectList(db.ClassroomDay2, "ClassroomDay2_Id", "ClassroomDay2_Name", register.ClassroomDay2_Id);
            ViewBag.Login_Id = new SelectList(db.Logins, "Login_Id", "l_Firstname", register.Login_Id);
            ViewBag.StatusPay_Id = new SelectList(db.StatusPays, "StatusPay_Id", "StatusPay_Name", register.StatusPay_Id);
            return View(register);
        }

        // GET: Registers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // POST: Registers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Register register = db.Registers.Find(id);
            db.Registers.Remove(register);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

thfmsemi/Views/Registers/Create.cshtml
@model thfmsemi.Models.Register

@{
    ViewBag.Title = "Register";
}
@if (Session["Email"] != null)
{
    <br />
    <h4>สวัสดีค่ะ คุณ <font color="green"><b>@Session["FirstName"].ToString() @Session["LastName"].ToString()</b></font> </h4>
    <h4>@*Welcame @Session["UserID"].ToString()*@</h4>
}
<h2>ระบบลงทะเบียนผู้เข้าร่วมสัมมนา</h2>
<div class="table-responsive">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>The 2<sup>nd</sup> Thailand Healthcare Facility Management Excellence Seminar</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        if (ViewBag.Error != null)
        {
            <h2><font color="Red">@ViewBag.Error</font></h2>
        }
        int count = 0;
        <div border="0" cellpadding="0" cellspacing="0" style="border-color:white" class="table-responsive">
            <table border="0" cellpadding="0" cellspacing="0" class="table table-responsive bg btn-group-vertical">
                <tr style="border-color:white">
                    <th style="border-color:white">@Html.Label("เพิ่มรายชื่อผู้เข้าร่วมสัมมนา")</th>
                    <th style="border-color:white"></th>
                    <th style="border-color:white">@Html.EditorFor(model => model.DateRegister, new { htmlAttributes = new { @class = "", Value = System.DateTime.Now.ToString(@"yyyy\/MM\/dd hh:mm:ss tt"), @readonly = "readonly" } })</th>
                    <th style="border-color:white">@Html.ValidationMessageFor(model => model.DateRegister, "", new { @class = "text-danger" })</th>
                </tr>
                <tr>
                    <th>คำนำหน้าชื่อ</th>
                    <th>ชื่อ</th>
                    <th>นามสกุล</th>
                </tr>
                <tr>
                    <td style="border-color:white">@Html.EditorFor(model => model.Titlename, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })</td>
                    <td style="border-color:white">@Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })</td>
                    <td style="border-color:white">@Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })</td>
                </tr>
                <tr>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Titlename, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })</td>
                </tr>

                <tr style="border-color:white">
                    <th>ตำแหน่ง</th>
                    <th>อีเมล์</th>
                    <th>เบอร์โทรศัพท์</th>
                </tr>
                <tr style="border-color:white">
                    <td style="border-color:white">@Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })</td>
                    <td style="border-color:white">@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })</td>
                    <td style="border-color:white">@Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control", onkeypress = "validate(event)", maxlength = "12" } })</td>
                </tr>
                <tr style="border-color:white">
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })</td>
                </tr>
                <tr style="border-color:white">
                    <td style="border-color:white"><a href="http://www.thfmseminar.com/index/schedule" target="_blank">รายละเอียดกำหนดการ</a></td>
                </tr>
                <tr style="border-color:white">
                    <th>สำรองที่นั่งช่วงบ่ายวันที่ 17 พ.ย.59</th>
                    <th>สำรองที่นั่งช่วงบ่ายวันที่ 18 พ.ย.59</th>
                    <th></th>
                </tr>
                <tr style="border-color:white">
                    <td style="border-color:white">@Html.DropDownList("ClassroomDay1_Id", null, htmlAttributes: new { @class = "form-control" })</td>
                    <td style="border-color:white">@Html.DropDownList("ClassroomDay2_Id", null, htmlAttributes: new { @class = "form-control" })</td>
                </tr>
                <tr style="border-color:white">
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.ClassroomDay1_Id, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white">@Html.ValidationMessageFor(model => model.ClassroomDay2_Id, "", new { @class = "text-danger" })</td>
                    <td style="border-color:white"></td>
                </tr>
                <tr>
                    <td><input type="submit" value="เพิ่มรายชื่อผู้เข้าร่วมสัมมนา" class="btn btn-primary" /></td>
                    <td><input name="b2" value="ยืนยันรายชื่อผู้สมัครทั้งหมด" onclick="location.href='@Url.Action("Create", "Bills")';" class="btn btn-success"></td>
                </tr>
            </table>
        </div>
        <div>
            <b><font color="red">* กรุณากดปุ่ม "เพิ่มรายชื่อผู้เข้าร่วมสัมมนา" (สามารถเพิ่มได้หลายท่าน)</font></b><br />
            <b><font color="red">ก่อนกดปุ่ม "ยืนยันรายชื่อผู้สมัครทั้งหมด" ตรวจสอบรายชื่อผู้เข้าร่วมสัมมนาได้ที่ตารางด้านล่าง</font></b>
        </div>


        @*@Html.ActionLink("Next", "Create", "Bills")*@

    }
    <b><br />รายชื่อผู้เข้าร่วมสัมมนา</b>
    <table class="table table-responsive">
        <tr class="label-info">
            <th>
                @*@Html.DisplayNameFor(model => model.Titlename)*@คำนำหน้าชื่อ
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Fristname)*@ชื่อ
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Lastname)*@นามสกุล
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Position)*@ตำแหน่ง
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Email)*@อีเมล์
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Tel)*@เบอร์โทรศัพท์
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ClassroomDay1.ClassroomDay1_Name)*@สำรองที่นั่งวันที่ 1
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ClassroomDay2.ClassroomDay2_Name)*@สำรองที่นั่งวันที่ 2
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.StatusPay.StatusPay_Name)*@สถานะ
            </th>
            <th>ลบข้อมูล</th>
        </tr>
        @foreach (var item in (IEnumerable<thfmsemi.Models.Register>)ViewBag.Name)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titlename)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Firstname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassroomDay1.ClassroomDay1_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassroomDay2.ClassroomDay2_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusPay.StatusPay_Name)
                </td>
                <td>
                    @if (item.StatusPay.StatusPay_Name == " ")
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.Register_Id })
                    }
                </td>
            </tr>
        }

    </table>
    <div>
        <p><br /></p>
        <p style="text-align: left;"><br /><img src="~/img/sl0.JPG" /></p>
        <p style="text-align: left;"><img src="~/img/sl.JPG" /></p>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    {
        function validate(evt) {
            var theEvent = evt || window.event;
            var key = theEvent.keyCode || theEvent.which;
            key = String.fromCharCode(key);
            var regex = /[0-9]|\./;
            if (!regex.test(key)) {
                theEvent.returnValue = false;
                if (theEvent.preventDefault) theEvent.preventDefault();
            }
        }
    }
</script>